# Generated by Django 5.0.6 on 2024-06-17 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
