# Generated by Django 5.0.9 on 2024-10-25 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commentbox', '0003_customer_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='phone',
            new_name='phonenumber',
        ),
    ]
